### ISSUE TITLE
Stakeholder Review Checklist

### ISSUE THREAD

**Issue by chrisheninger** [elm-street-technology/elevate-marketing-site#14]
## Events
https://elevate-marketing-site.netlify.com/events
- [ ] Is this list up-to-date? I manually input through the end of September based on the existing list. Please double-check this list and let me know if anything needs added/edited/removed.

## Markets
https://elevate-marketing-site.netlify.com/markets
- [ ] Is this list up-to-date? If not, what needs added/edited/removed?

## Testimonials
https://elevate-marketing-site.netlify.com/testimonials
- [ ] Need actual tagline for section under "Customer Testimonials"
- [ ] Need 2 long testimonials for top and bottom sections
- [ ] Need 3 short testimonials for middle section

## Legal
https://elevate-marketing-site.netlify.com/terms-of-service
https://elevate-marketing-site.netlify.com/privacy
https://elevate-marketing-site.netlify.com/dmca
- [ ] I copied these directly from the existing site. My only concern is on the Terms– towards the bottom there's some stuff that looks like it got copy/pasted in (I HAVE READ THIS AGREEMENT...)
- [ ] Also on Terms– we have a nice numbered list but then towards the end it looks like a few extra points were added? Do we want to give those numbers too?

## Webinars
https://elevate-marketing-site.netlify.com/webinars
- [ ] Is this list up-to-date? Are all the register links going to the correct places?

## Blog
https://elevate-marketing-site.netlify.com/blog
- [ ] I copied these directly from the existing site. Have a look, let me know if anything is out of place or needs updated.

## Get Started
https://elevate-marketing-site.netlify.com/get-started
- [ ] The copy on this page is taken directly from the existing site, do we want to update it?
- [ ] I removed the "Media Inquiry" mailto link from the bottom of this form (see http://tryelevate.com/getStarted/ )– I think that belongs on an actual contact or about us page

**Comment by chrisheninger** [comment]
Moved to a Google Doc.
